# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1brpnfXjzjsLaz_s8wkPsh2kOkcAZkNkI
"""

# ==============================================================================
# app.py — ProphetNet Headline Generator
# Procesamiento de Datos Secuenciales
# ==============================================================================

import streamlit as st
import torch
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import io, base64, warnings
warnings.filterwarnings("ignore")

from rouge_score import rouge_scorer as rouge_lib

# ── Configuración de página ───────────────────────────────────────────────────
st.set_page_config(
    page_title="ProphetNet — Headline Generator",
    page_icon="🔮",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── CSS global ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Sans:wght@300;400;500;600&family=DM+Mono:wght@400;500&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
html,body,[data-testid="stAppViewContainer"]{background:#0a0a0f!important;color:#e8e6e0!important;font-family:'DM Sans',sans-serif!important}
[data-testid="stAppViewContainer"]>.main{background:#0a0a0f!important}
[data-testid="stHeader"]{background:transparent!important}
[data-testid="stSidebar"]{background:#0e0e18!important;border-right:1px solid rgba(255,255,255,0.06)!important}
.block-container{padding:0!important;max-width:100%!important}
#MainMenu,footer,header{visibility:hidden}
[data-testid="stToolbar"]{display:none}

/* Hero */
.hero{position:relative;padding:56px 80px 44px;border-bottom:1px solid rgba(255,255,255,0.06);overflow:hidden}
.hero::before{content:'';position:absolute;top:-120px;right:-120px;width:500px;height:500px;background:radial-gradient(circle,rgba(139,92,246,0.12) 0%,transparent 70%);pointer-events:none}
.hero-eyebrow{font-family:'DM Mono',monospace;font-size:11px;letter-spacing:0.18em;color:rgba(139,92,246,0.9);text-transform:uppercase;margin-bottom:16px}
.hero-title{font-family:'DM Serif Display',serif;font-size:clamp(36px,5vw,62px);font-weight:400;line-height:1.05;color:#f0ede6;margin-bottom:12px}
.hero-title em{font-style:italic;color:rgba(139,92,246,0.85)}
.hero-desc{font-size:14px;font-weight:300;color:rgba(232,230,224,0.5);max-width:580px;line-height:1.7;margin-bottom:28px}
.hero-stats{display:flex;gap:36px;flex-wrap:wrap}
.stat-value{font-family:'DM Serif Display',serif;font-size:26px;color:#f0ede6;line-height:1}
.stat-label{font-size:10px;font-weight:300;color:rgba(232,230,224,0.35);margin-top:4px;letter-spacing:0.05em}

/* Campos */
.field-label{font-family:'DM Mono',monospace;font-size:10px;letter-spacing:0.15em;color:rgba(232,230,224,0.4);text-transform:uppercase;margin-bottom:10px;display:block}
.stTextArea textarea{background:rgba(255,255,255,0.03)!important;border:1px solid rgba(255,255,255,0.08)!important;border-radius:12px!important;color:#e8e6e0!important;font-family:'DM Sans',sans-serif!important;font-size:14px!important;font-weight:300!important;line-height:1.7!important;padding:18px!important}
.stTextArea textarea:focus{border-color:rgba(139,92,246,0.4)!important}
.stTextArea label,.stSelectbox label,.stSlider label{display:none!important}
.stSelectbox>div>div{background:rgba(255,255,255,0.03)!important;border:1px solid rgba(255,255,255,0.08)!important;border-radius:10px!important;color:#e8e6e0!important;font-family:'DM Sans',sans-serif!important}
.stButton>button{width:100%!important;background:rgba(139,92,246,0.15)!important;border:1px solid rgba(139,92,246,0.35)!important;border-radius:10px!important;color:rgba(232,230,224,0.9)!important;font-family:'DM Sans',sans-serif!important;font-size:13px!important;font-weight:500!important;padding:14px 28px!important;transition:all 0.2s!important}
.stButton>button:hover{background:rgba(139,92,246,0.25)!important;border-color:rgba(139,92,246,0.6)!important}

/* Output */
.output-card{background:rgba(139,92,246,0.06);border:1px solid rgba(139,92,246,0.2);border-radius:16px;padding:24px 28px;margin-bottom:24px}
.output-eyebrow{font-family:'DM Mono',monospace;font-size:10px;letter-spacing:0.15em;color:rgba(139,92,246,0.7);text-transform:uppercase;margin-bottom:12px}
.output-headline{font-family:'DM Serif Display',serif;font-size:24px;font-weight:400;color:#f0ede6;line-height:1.3;font-style:italic}

/* Métricas ROUGE */
.rouge-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:24px}
.rouge-card{background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.07);border-radius:12px;padding:16px 14px;text-align:center}
.rouge-f1{font-family:'DM Serif Display',serif;font-size:22px;color:#f0ede6;line-height:1;margin-bottom:4px}
.rouge-sub{font-family:'DM Mono',monospace;font-size:9px;color:rgba(232,230,224,0.3);letter-spacing:0.08em;margin-bottom:8px;text-transform:uppercase}
.rouge-pr{font-family:'DM Mono',monospace;font-size:10px;color:rgba(232,230,224,0.45);line-height:1.6}
.rouge-label{font-family:'DM Mono',monospace;font-size:9px;color:rgba(139,92,246,0.6);letter-spacing:0.12em;text-transform:uppercase;margin-top:6px}

/* Atención */
.attn-row{display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid rgba(255,255,255,0.04)}
.attn-row:last-child{border-bottom:none}
.attn-token{font-family:'DM Mono',monospace;font-size:11px;color:rgba(232,230,224,0.6);width:86px;flex-shrink:0}
.attn-bar-wrap{flex:1;height:4px;background:rgba(255,255,255,0.06);border-radius:99px;overflow:hidden}
.attn-bar{height:100%;border-radius:99px;background:linear-gradient(90deg,rgba(139,92,246,0.7),rgba(20,184,166,0.7))}
.attn-source{font-family:'DM Mono',monospace;font-size:10px;color:rgba(232,230,224,0.3);width:110px;flex-shrink:0;text-align:right;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}

/* Sidebar */
.sb-title{font-family:'DM Mono',monospace;font-size:10px;letter-spacing:0.15em;color:rgba(139,92,246,0.8);text-transform:uppercase;margin-bottom:14px;padding-bottom:8px;border-bottom:1px solid rgba(255,255,255,0.05)}
.sb-row{display:flex;justify-content:space-between;align-items:baseline;padding:5px 0;border-bottom:1px solid rgba(255,255,255,0.03)}
.sb-key{font-family:'DM Mono',monospace;font-size:10px;color:rgba(232,230,224,0.4)}
.sb-val{font-family:'DM Serif Display',serif;font-size:13px;color:#f0ede6}
.sb-block{background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.05);border-radius:10px;padding:14px;margin-bottom:16px}
.sb-block p{font-size:12px;color:rgba(232,230,224,0.45);line-height:1.65;margin-top:6px}
.sb-tag{display:inline-block;font-family:'DM Mono',monospace;font-size:9px;background:rgba(139,92,246,0.15);border:1px solid rgba(139,92,246,0.3);border-radius:6px;padding:2px 8px;color:rgba(139,92,246,0.9);margin:2px}

/* Misc */
.section-title{font-family:'DM Mono',monospace;font-size:10px;letter-spacing:0.15em;color:rgba(232,230,224,0.3);text-transform:uppercase;margin-bottom:14px;padding-bottom:8px;border-bottom:1px solid rgba(255,255,255,0.05)}
.divider{height:1px;background:rgba(255,255,255,0.05);margin:24px 0}
.lim-item{border-left:2px solid rgba(139,92,246,0.4);padding:10px 14px;margin-bottom:10px;background:rgba(255,255,255,0.02);border-radius:0 8px 8px 0}
.lim-title{font-family:'DM Mono',monospace;font-size:10px;color:rgba(139,92,246,0.8);letter-spacing:0.1em;text-transform:uppercase;margin-bottom:4px}
.lim-desc{font-size:12px;color:rgba(232,230,224,0.45);line-height:1.6}
</style>
""", unsafe_allow_html=True)


# ── Carga del modelo (cacheado) ───────────────────────────────────────────────
@st.cache_resource(show_spinner=False)
def cargar_modelo():
    from transformers import ProphetNetForConditionalGeneration, ProphetNetTokenizer
    MODEL = "microsoft/prophetnet-large-uncased-cnndm"
    tokenizer = ProphetNetTokenizer.from_pretrained(MODEL)
    model = ProphetNetForConditionalGeneration.from_pretrained(MODEL)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    model.eval()
    return model, tokenizer, device


# ── Inferencia ────────────────────────────────────────────────────────────────
def generar_titular(model, tokenizer, device, articulo,
                    num_beams=4, max_length=60, min_length=8,
                    no_repeat_ngram_size=3):
    """
    Pipeline de inferencia: tokenización → beam search → decodificación.
    El n-stream decoder de ProphetNet opera solo en entrenamiento.
    En inferencia solo actúa el main stream, de forma autoregresiva.
    """
    inputs = tokenizer(
        articulo.lower(), return_tensors="pt",
        truncation=True, max_length=512
    )
    input_ids      = inputs["input_ids"].to(device)
    attention_mask = inputs["attention_mask"].to(device)
    with torch.no_grad():
        output_ids = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            num_beams=num_beams,
            max_length=max_length,
            min_length=min_length,
            no_repeat_ngram_size=no_repeat_ngram_size,
            early_stopping=True,
        )
    return tokenizer.decode(output_ids[0], skip_special_tokens=True)


# ── Extracción de atención (corregida) ────────────────────────────────────────
def extraer_atencion(model, tokenizer, device, articulo, titular, capa=-1):
    """
    Extrae pesos de cross-attention: softmax(Q·Kᵀ / √d_head).
    Q viene del decoder (titular), K y V vienen del encoder (artículo).
    Se hace un forward pass teacher-forced con el titular ya generado.
    Los pesos vienen post-softmax: no se aplica exp().
    Normalización defensiva garantiza que cada fila sume exactamente 1.
    """
    inputs = tokenizer(
        articulo.lower(), return_tensors="pt",
        truncation=True, max_length=512
    ).to(device)
    labels = tokenizer(
        titular, return_tensors="pt",
        truncation=True, max_length=128
    ).input_ids.to(device)

    with torch.no_grad():
        outputs = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            decoder_input_ids=labels,
            output_attentions=True,
        )

    # Extrae la capa solicitada y promedia las 16 cabezas de atención.
    # Shape original: (batch=1, num_heads=16, seq_dec, seq_enc)
    cross_attn = outputs.cross_attentions[capa].squeeze(0).mean(dim=0).cpu().numpy()

    # Normalización defensiva (los pesos ya son post-softmax, esto garantiza
    # que la suma sea exactamente 1.0 sin distorsionar la distribución).
    row_sums = cross_attn.sum(axis=-1, keepdims=True)
    row_sums = np.where(row_sums == 0, 1, row_sums)
    cross_attn = cross_attn / row_sums

    tok_in  = [t for t in tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
               if t not in ["[PAD]", "[CLS]"]]
    tok_out = [t for t in tokenizer.convert_ids_to_tokens(labels[0])
               if t not in ["[PAD]", "[SEP]"]]

    cross_attn = cross_attn[:len(tok_out), :len(tok_in)]
    return cross_attn, tok_in, tok_out


# ── ROUGE dinámico ────────────────────────────────────────────────────────────
def calcular_rouge(titular_generado, titular_real):
    """
    Calcula ROUGE-1, ROUGE-2 y ROUGE-L en tiempo real.
    Retorna Precision, Recall y F1 para cada métrica.
    """
    scorer = rouge_lib.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)
    scores = scorer.score(target=titular_real, prediction=titular_generado)
    return {
        "rouge1": scores["rouge1"],
        "rouge2": scores["rouge2"],
        "rougeL": scores["rougeL"],
    }


# ── Heatmap como PNG en base64 ────────────────────────────────────────────────
def heatmap_b64(attn, tok_in, tok_out, titulo_capa=""):
    max_in  = min(30, len(tok_in))
    max_out = min(18, len(tok_out))
    toks_x  = [t.replace("##", "") for t in tok_in[:max_in]]
    toks_y  = [t.replace("##", "") for t in tok_out[:max_out]]
    attn_plot = attn[:max_out, :max_in]

    fig, ax = plt.subplots(figsize=(max(10, max_in * 0.46), max(4, max_out * 0.44)))
    fig.patch.set_facecolor("#0e0e16")
    ax.set_facecolor("#0e0e16")

    sns.heatmap(
        attn_plot, ax=ax,
        xticklabels=toks_x,
        yticklabels=toks_y,
        cmap="rocket_r",
        linewidths=0.3, linecolor="#111",
        vmin=0,
        cbar_kws={"label": "softmax(Q·Kᵀ/√d)", "shrink": 0.8},
    )

    # Resalta el token de mayor atención por fila (azul)
    for i in range(min(max_out, attn_plot.shape[0])):
        j_max = int(np.argmax(attn_plot[i]))
        ax.add_patch(plt.Rectangle(
            (j_max, i), 1, 1,
            fill=False, edgecolor="#6699ff", lw=1.8
        ))

    titulo_completo = "Cross-Attention · ProphetNet"
    if titulo_capa:
        titulo_completo += f" — {titulo_capa}"
    ax.set_title(titulo_completo, color="#ccc", fontsize=9, pad=10)
    ax.set_xlabel("Encoder tokens — artículo de entrada\n(Q: decoder | K,V: encoder)",
                  color="#888", fontsize=8)
    ax.set_ylabel("Decoder tokens — titular generado", color="#888", fontsize=8)
    ax.tick_params(axis="x", colors="#aaa", labelsize=7, rotation=50)
    ax.tick_params(axis="y", colors="#aaa", labelsize=7, rotation=0)
    ax.collections[0].colorbar.ax.tick_params(colors="#888", labelsize=7)
    ax.collections[0].colorbar.set_label("softmax(Q·Kᵀ/√d)", color="#888", fontsize=7)

    plt.tight_layout(pad=1.5)
    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=150, facecolor="#0e0e16", bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode(), buf.getvalue()


# ── Datos de ejemplos ─────────────────────────────────────────────────────────
EJEMPLOS = {
    "🇺🇸 Diplomacia — Bolivia": {
        "articulo": (
            "the us state department said wednesday it had received no formal word from bolivia "
            "that it was expelling the us ambassador there but said the charges made against him "
            "are baseless and that he enjoys the full confidence of the secretary of state."
        ),
        "titular_real": "us rejects charges against its ambassador in bolivia",
    },
    "🦕 Dinosaurio en Argentina": {
        "articulo": (
            "scientists have discovered a new species of dinosaur in argentina that they believe "
            "is one of the largest creatures ever to have walked the earth. the titanosaur, "
            "which lived about 100 million years ago, is estimated to have weighed 70 tons and "
            "measured 40 meters from head to tail."
        ),
        "titular_real": "scientists discover one of the largest dinosaurs ever found in argentina",
    },
    "🍎 Apple ganancias récord": {
        "articulo": (
            "apple has announced its quarterly earnings, reporting record revenue of 90 billion dollars "
            "driven by strong iphone sales and growth in its services division. the company also "
            "announced a new stock buyback program worth 90 billion dollars and increased its "
            "quarterly dividend by four percent."
        ),
        "titular_real": "apple reports record quarterly revenue driven by iphone and services growth",
    },
    "🚀 NASA en Marte": {
        "articulo": (
            "nasa has confirmed that its perseverance rover has successfully collected its first rock "
            "sample from the surface of mars. the sample, extracted from a rock called rochette, "
            "will eventually be returned to earth for detailed scientific analysis. scientists hope "
            "the samples will help answer whether life ever existed on mars."
        ),
        "titular_real": "nasa perseverance rover collects first mars rock sample",
    },
    "🌍 OMS emergencia global": {
        "articulo": (
            "the world health organization declared a global health emergency on thursday as a new "
            "respiratory virus continues to spread across multiple continents. health officials "
            "urged governments to increase surveillance and strengthen their health systems "
            "while researchers race to develop vaccines and treatments."
        ),
        "titular_real": "who declares global health emergency over new respiratory virus",
    },
    "🌿 Deforestación Amazonia": {
        "articulo": (
            "the amazon rainforest is losing approximately 10000 square kilometers of forest per year "
            "due to deforestation. scientists warn that if current trends continue, the ecosystem could "
            "reach a tipping point within the next decade, causing irreversible damage to global climate "
            "patterns and biodiversity. brazil environment ministry reported a 17 percent increase "
            "in deforestation rates compared to the previous year."
        ),
        "titular_real": "amazon deforestation hits 17 percent rise as scientists warn of tipping point",
    },
    "🏦 Fed sube tasas": {
        "articulo": (
            "the federal reserve raised interest rates by 75 basis points on wednesday, the largest "
            "increase since 1994, as policymakers moved aggressively to combat inflation that has "
            "reached a 40-year high. chair jerome powell signaled that additional large increases "
            "are likely at coming meetings."
        ),
        "titular_real": "fed raises rates by 75 basis points in largest hike since 1994",
    },
    "🤖 Google presenta Gemini": {
        "articulo": (
            "google has unveiled its new artificial intelligence model called gemini, which the company "
            "claims outperforms gpt-4 on a majority of benchmarks tested. the model is multimodal, "
            "capable of understanding text, images, audio and video. google plans to integrate gemini "
            "across its product lineup starting next year."
        ),
        "titular_real": "google unveils gemini ai model claiming to surpass gpt-4",
    },
    "✏️ Escribe el tuyo...": {
        "articulo": "",
        "titular_real": "",
    },
}

CAPAS = {
    "Capa 1 (superficial)":  0,
    "Capa 4":                 3,
    "Capa 8 (media)":         7,
    "Capa 12 (profunda) ✦":  -1,
}


# ══════════════════════════════════════════════════════════════════════════════
# SIDEBAR — Arquitectura del modelo
# ══════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown('<div class="sb-title">Arquitectura ProphetNet</div>', unsafe_allow_html=True)

    params = [
        ("Parámetros",        "485 M"),
        ("Capas encoder",     "12"),
        ("Capas decoder",     "12"),
        ("d_model",           "1024"),
        ("Attention heads",   "16"),
        ("d_head = d/h",      "64"),
        ("FFN interior",      "4096"),
        ("N-gram (n)",        "2"),
        ("Vocabulario",       "30 522"),
        ("Max tokens enc.",   "512"),
    ]
    rows = "".join(
        f'<div class="sb-row"><span class="sb-key">{k}</span>'
        f'<span class="sb-val">{v}</span></div>'
        for k, v in params
    )
    st.markdown(f'<div class="sb-block">{rows}</div>', unsafe_allow_html=True)

    st.markdown('<div class="sb-title" style="margin-top:20px">Mecanismo Q · K · V</div>',
                unsafe_allow_html=True)
    st.markdown("""
    <div class="sb-block">
      <p><b style="color:#e8e6e0">Cross-Attention</b><br>
      Q = estado del <b style="color:#8b7cf6">decoder</b> · W<sub>q</sub><br>
      K = estado del <b style="color:#14b8a6">encoder</b> · W<sub>k</sub><br>
      V = estado del <b style="color:#14b8a6">encoder</b> · W<sub>v</sub><br><br>
      <code style="font-size:11px;color:#aaa">softmax(Q·Kᵀ / √64) · V</code><br><br>
      Los pesos del heatmap son exactamente <code style="font-size:11px;color:#aaa">softmax(Q·Kᵀ/√d)</code>:
      cuánto atiende cada token del titular a cada token del artículo.</p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown('<div class="sb-title" style="margin-top:4px">N-stream Decoder</div>',
                unsafe_allow_html=True)
    st.markdown("""
    <div class="sb-block">
      <p><b style="color:#e8e6e0">Entrenamiento (n=2):</b><br>
      Main stream → predice y<sub>t+1</sub><br>
      Predict stream → predice y<sub>t+2</sub><br>
      Cada stream tiene W<sub>q</sub>, W<sub>k</sub>, W<sub>v</sub> propias.<br><br>
      <b style="color:#e8e6e0">Inferencia:</b><br>
      Solo opera el main stream.<br>
      El predict stream se desactiva.<br>
      La ventaja n-gram está en los pesos aprendidos.</p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown('<div class="sb-title" style="margin-top:4px">vs otros modelos</div>',
                unsafe_allow_html=True)
    comparacion = [
        ("BERT",       "Encoder only",  "No"),
        ("GPT-2",      "Decoder only",  "No"),
        ("BART",       "Enc-Dec",       "No"),
        ("T5",         "Enc-Dec",       "No"),
        ("ProphetNet", "Enc-Dec",       "Sí ✦"),
    ]
    filas_cmp = "".join(
        f'<div class="sb-row">'
        f'<span class="sb-key" style="color:{"rgba(139,92,246,0.9)" if m=="ProphetNet" else "rgba(232,230,224,0.4)"}'
        f'">{m}</span>'
        f'<span style="font-size:10px;color:rgba(232,230,224,0.35)">{arq}</span>'
        f'<span style="font-size:10px;color:{"rgba(139,92,246,0.9)" if ns=="Sí ✦" else "rgba(232,230,224,0.25)"}'
        f'">{ns}</span>'
        f'</div>'
        for m, arq, ns in comparacion
    )
    st.markdown(
        f'<div class="sb-block"><div class="sb-row">'
        f'<span class="sb-key">Modelo</span>'
        f'<span style="font-size:10px;color:rgba(232,230,224,0.3)">Tipo</span>'
        f'<span style="font-size:10px;color:rgba(232,230,224,0.3)">N-stream</span>'
        f'</div>{filas_cmp}</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div style="margin-top:20px;font-family:DM Mono,monospace;font-size:9px;'
        'color:rgba(232,230,224,0.2);line-height:1.6">'
        'Yan et al. (2020) · arXiv:2001.04063<br>'
        'microsoft/prophetnet-large-uncased-cnndm<br>'
        'Procesamiento de Datos Secuenciales</div>',
        unsafe_allow_html=True
    )


# ══════════════════════════════════════════════════════════════════════════════
# HERO
# ══════════════════════════════════════════════════════════════════════════════
st.markdown(
    '<div class="hero">'
    '<div class="hero-eyebrow">Procesamiento de Datos Secuenciales · Proyecto Final</div>'
    '<div class="hero-title">Prophet<em>Net</em> — Headline Generator</div>'
    '<div class="hero-desc">'
    'Transformer encoder-decoder con <em>future n-gram prediction</em> (Yan et al., 2020). '
    'Ingresa un artículo, observa la inferencia y explora el mecanismo de cross-attention Q·K·V.'
    '</div>'
    '<div class="hero-stats">'
    '<div class="stat-item"><div class="stat-value">485M</div><div class="stat-label">Parámetros</div></div>'
    '<div class="stat-item"><div class="stat-value">12+12</div><div class="stat-label">Capas Enc/Dec</div></div>'
    '<div class="stat-item"><div class="stat-value">16</div><div class="stat-label">Attention heads</div></div>'
    '<div class="stat-item"><div class="stat-value">n=2</div><div class="stat-label">N-gram prediction</div></div>'
    '<div class="stat-item"><div class="stat-value">64</div><div class="stat-label">d_head</div></div>'
    '</div></div>',
    unsafe_allow_html=True,
)


# ══════════════════════════════════════════════════════════════════════════════
# TABS PRINCIPALES
# ══════════════════════════════════════════════════════════════════════════════
tab_gen, tab_lim = st.tabs(["⟶  Generación e inferencia", "⚠  Limitaciones del modelo"])


# ──────────────────────────────────────────────────────────────────────────────
# TAB 1 — Generación
# ──────────────────────────────────────────────────────────────────────────────
with tab_gen:
    col_left, col_right = st.columns([1, 1], gap="small")

    # ── Columna izquierda: inputs ──────────────────────────────────────────────
    with col_left:
        st.markdown('<div style="padding:36px 48px 0">', unsafe_allow_html=True)

        st.markdown('<span class="field-label">Selecciona un ejemplo</span>',
                    unsafe_allow_html=True)
        seleccion = st.selectbox("_", list(EJEMPLOS.keys()),
                                 label_visibility="collapsed")

        st.markdown('<div style="height:12px"></div>', unsafe_allow_html=True)
        st.markdown('<span class="field-label">Artículo de noticias (en inglés)</span>',
                    unsafe_allow_html=True)
        articulo = st.text_area(
            "_",
            value=EJEMPLOS[seleccion]["articulo"],
            height=200,
            placeholder="Paste a news article here...",
            label_visibility="collapsed",
        )

        st.markdown('<div style="height:10px"></div>', unsafe_allow_html=True)
        st.markdown('<span class="field-label">Titular de referencia (ground truth — opcional)</span>',
                    unsafe_allow_html=True)
        titular_ref = st.text_input(
            "_",
            value=EJEMPLOS[seleccion]["titular_real"],
            placeholder="Escribe el titular real para calcular ROUGE...",
            label_visibility="collapsed",
        )

        st.markdown('<div class="divider"></div>', unsafe_allow_html=True)
        st.markdown('<span class="field-label">Parámetros de generación</span>',
                    unsafe_allow_html=True)

        c1, c2 = st.columns(2)
        with c1:
            st.markdown('<span class="field-label">Beam search</span>',
                        unsafe_allow_html=True)
            num_beams = st.slider("_", 1, 8, 4, label_visibility="collapsed")
        with c2:
            st.markdown('<span class="field-label">Max tokens output</span>',
                        unsafe_allow_html=True)
            max_length = st.slider("_", 20, 80, 50, label_visibility="collapsed")

        st.markdown('<div style="height:6px"></div>', unsafe_allow_html=True)
        st.markdown('<span class="field-label">Capa de atención a visualizar</span>',
                    unsafe_allow_html=True)
        capa_nombre = st.selectbox("_capa", list(CAPAS.keys()),
                                   index=3, label_visibility="collapsed")
        capa_idx = CAPAS[capa_nombre]

        st.markdown('<div style="height:10px"></div>', unsafe_allow_html=True)
        generar = st.button("⟶  Generar titular", use_container_width=True)
        st.markdown('</div>', unsafe_allow_html=True)

    # ── Columna derecha: outputs ───────────────────────────────────────────────
    with col_right:
        st.markdown('<div style="padding:36px 48px 0">', unsafe_allow_html=True)

        if generar and articulo.strip():

            # 1. Carga del modelo
            with st.spinner("Cargando modelo ProphetNet (485M parámetros)..."):
                model_obj, tokenizer_obj, device_obj = cargar_modelo()

            # 2. Generación del titular
            with st.spinner("Generando titular con beam search..."):
                titular = generar_titular(
                    model_obj, tokenizer_obj, device_obj, articulo,
                    num_beams=num_beams, max_length=max_length,
                )

            # Titular generado
            st.markdown(
                '<div class="output-card">'
                '<div class="output-eyebrow">Titular generado · ProphetNet</div>'
                f'<div class="output-headline">{titular}</div>'
                '</div>',
                unsafe_allow_html=True,
            )

            # 3. ROUGE dinámico (solo si hay titular de referencia)
            if titular_ref.strip():
                with st.spinner("Calculando métricas ROUGE..."):
                    rouge_scores = calcular_rouge(titular, titular_ref.strip())

                r1 = rouge_scores["rouge1"]
                r2 = rouge_scores["rouge2"]
                rl = rouge_scores["rougeL"]

                st.markdown(
                    '<div class="section-title">Métricas ROUGE vs titular de referencia'
                    ' — calculadas en tiempo real</div>'
                    '<div class="rouge-grid">'

                    f'<div class="rouge-card">'
                    f'<div class="rouge-f1">{r1.fmeasure:.3f}</div>'
                    f'<div class="rouge-sub">F1-Score</div>'
                    f'<div class="rouge-pr">P: {r1.precision:.3f} · R: {r1.recall:.3f}</div>'
                    f'<div class="rouge-label">ROUGE-1</div>'
                    f'</div>'

                    f'<div class="rouge-card">'
                    f'<div class="rouge-f1">{r2.fmeasure:.3f}</div>'
                    f'<div class="rouge-sub">F1-Score</div>'
                    f'<div class="rouge-pr">P: {r2.precision:.3f} · R: {r2.recall:.3f}</div>'
                    f'<div class="rouge-label">ROUGE-2</div>'
                    f'</div>'

                    f'<div class="rouge-card">'
                    f'<div class="rouge-f1">{rl.fmeasure:.3f}</div>'
                    f'<div class="rouge-sub">F1-Score</div>'
                    f'<div class="rouge-pr">P: {rl.precision:.3f} · R: {rl.recall:.3f}</div>'
                    f'<div class="rouge-label">ROUGE-L</div>'
                    f'</div>'

                    '</div>',
                    unsafe_allow_html=True,
                )
            else:
                st.markdown(
                    '<div style="font-family:DM Mono,monospace;font-size:10px;'
                    'color:rgba(232,230,224,0.25);margin-bottom:20px;padding:12px;'
                    'border:1px dashed rgba(255,255,255,0.07);border-radius:8px">'
                    'Ingresa un titular de referencia en el campo izquierdo '
                    'para ver las métricas ROUGE calculadas en tiempo real.'
                    '</div>',
                    unsafe_allow_html=True,
                )

            # 4. Extracción de atención
            with st.spinner(f"Extrayendo cross-attention — {capa_nombre}..."):
                attn, tok_in, tok_out = extraer_atencion(
                    model_obj, tokenizer_obj, device_obj,
                    articulo, titular, capa=capa_idx
                )

            # Heatmap
            st.markdown(
                f'<div class="section-title">Cross-attention heatmap · {capa_nombre}'
                ' — promedio 16 cabezas</div>',
                unsafe_allow_html=True,
            )
            b64_img, png_bytes = heatmap_b64(attn, tok_in, tok_out,
                                              titulo_capa=capa_nombre)
            st.markdown(
                '<div style="border-radius:12px;overflow:hidden;'
                'border:1px solid rgba(255,255,255,0.07);margin-bottom:12px">'
                f'<img src="data:image/png;base64,{b64_img}" style="width:100%;display:block">'
                '</div>',
                unsafe_allow_html=True,
            )

            # Botón de descarga del heatmap
            st.download_button(
                label="↓  Descargar heatmap PNG",
                data=png_bytes,
                file_name=f"cross_attention_{capa_nombre.replace(' ', '_')}.png",
                mime="image/png",
                use_container_width=True,
            )

            st.markdown('<div style="height:16px"></div>', unsafe_allow_html=True)

            # 5. Top-k por token generado
            st.markdown(
                '<div class="section-title">Análisis Q·K·V — token generado → '
                'top fuente en el artículo</div>',
                unsafe_allow_html=True,
            )

            rows_html = ""
            n_tokens = min(10, len(tok_out))
            n_in     = min(len(tok_in), attn.shape[1])
            for i in range(n_tokens):
                pesos     = attn[i, :n_in]
                top_idx   = int(np.argmax(pesos))
                tok_label = tok_out[i].replace("##", "")
                best_tok  = tok_in[top_idx].replace("##", "")
                best_val  = float(pesos[top_idx])
                bar_w     = min(100, int(best_val * 350))
                rows_html += (
                    '<div class="attn-row">'
                    f'<div class="attn-token">{tok_label}</div>'
                    '<div class="attn-bar-wrap">'
                    f'<div class="attn-bar" style="width:{bar_w}%"></div></div>'
                    f'<div class="attn-source">→ {best_tok} {best_val:.3f}</div>'
                    '</div>'
                )
            st.markdown(rows_html, unsafe_allow_html=True)

            st.markdown(
                '<div style="margin-top:12px;font-family:DM Mono,monospace;font-size:9px;'
                'color:rgba(232,230,224,0.2);line-height:1.6">'
                'Cada fila: el Query del token generado identificó ese token del artículo '
                'como la fuente de mayor peso · softmax(Q·Kᵀ/√64)'
                '</div>',
                unsafe_allow_html=True,
            )

        elif generar:
            st.markdown(
                '<div style="padding:40px;text-align:center;'
                'color:rgba(232,230,224,0.3);font-size:12px;font-family:DM Mono,monospace">'
                'INGRESA UN ARTÍCULO PRIMERO</div>',
                unsafe_allow_html=True,
            )
        else:
            st.markdown(
                '<div style="padding:70px 20px;text-align:center">'
                '<div style="font-size:42px;color:rgba(232,230,224,0.05);margin-bottom:16px">✦</div>'
                '<div style="font-size:10px;letter-spacing:0.15em;font-family:DM Mono,monospace;'
                'color:rgba(232,230,224,0.18)">SELECCIONA UN ARTÍCULO<br>Y PRESIONA GENERAR</div>'
                '</div>',
                unsafe_allow_html=True,
            )

        st.markdown('</div>', unsafe_allow_html=True)


# ──────────────────────────────────────────────────────────────────────────────
# TAB 2 — Limitaciones
# ──────────────────────────────────────────────────────────────────────────────
with tab_lim:
    st.markdown('<div style="padding:36px 60px">', unsafe_allow_html=True)
    st.markdown(
        '<div style="font-family:DM Mono,monospace;font-size:10px;letter-spacing:0.15em;'
        'color:rgba(139,92,246,0.8);text-transform:uppercase;margin-bottom:24px;'
        'padding-bottom:10px;border-bottom:1px solid rgba(255,255,255,0.05)">'
        'Limitaciones técnicas del modelo</div>',
        unsafe_allow_html=True,
    )

    limitaciones = [
        (
            "Checkpoint CNN/DM orientado a summarization",
            "El checkpoint <code>prophetnet-large-uncased-cnndm</code> fue fine-tuneado sobre "
            "CNN/DailyMail, donde los highlights son oraciones descriptivas largas, no titulares "
            "concisos. Para headline generation estricta existe el checkpoint entrenado sobre "
            "Gigaword (4M pares artículo → titular). Efecto visible: los titulares generados "
            "tienden a ser oraciones descriptivas más largas que un titular periodístico real.",
        ),
        (
            "N-stream desactivado en inferencia",
            "La innovación del n-stream self-attention opera <b>solo durante el entrenamiento</b> "
            "para calcular la función de pérdida multi-n-gram. En inferencia (<code>model.generate()</code>) "
            "solo actúa el main stream, de forma autoregresiva idéntica a un decoder estándar. "
            "La ventaja del n-stream se manifiesta indirectamente a través de los pesos aprendidos, "
            "no en la velocidad ni en la arquitectura de inferencia.",
        ),
        (
            "Límite de 512 tokens en el encoder",
            "El encoder de ProphetNet acepta un máximo de 512 tokens de entrada. Artículos más "
            "largos se truncan, potencialmente perdiendo información relevante del cuerpo del texto. "
            "Modelos posteriores como Longformer y BigBird extienden este límite a 4096+ tokens "
            "usando mecanismos de atención dispersa (sparse attention).",
        ),
        (
            "Solo inglés — vocabulario BERT-uncased",
            "El vocabulario es el de BERT-uncased (30,522 tokens en inglés). Artículos en otro "
            "idioma son procesados con el vocabulario inglés, lo que produce una tokenización "
            "subóptima con muchos tokens <code>##</code> (fragmentos de palabras no reconocidas). "
            "Fine-tuning en otros idiomas requeriría un tokenizer multilingual y corpus en el "
            "idioma objetivo.",
        ),
        (
            "Costo computacional — 485M parámetros",
            "ProphetNet requiere ~1.57 GB en memoria GPU (float32). La inferencia tarda "
            "2-8 segundos en GPU T4 y 30-60 segundos en CPU. No es apto para aplicaciones "
            "de tiempo real sin técnicas de optimización como cuantización int8/float16 "
            "o destilación de conocimiento.",
        ),
        (
            "Heatmap de atención — forward pass aproximado",
            "Los pesos de cross-attention se extraen mediante un forward pass teacher-forced "
            "(se usa el titular ya generado como <code>decoder_input_ids</code>). "
            "Esto es una aproximación: los pesos reales durante beam search difieren levemente "
            "porque beam search evalúa múltiples hipótesis en paralelo. Para análisis cualitativo "
            "y visualización es el método estándar en la literatura de NLP.",
        ),
    ]

    col_a, col_b = st.columns(2, gap="large")
    for i, (titulo, desc) in enumerate(limitaciones):
        col = col_a if i % 2 == 0 else col_b
        with col:
            st.markdown(
                f'<div class="lim-item">'
                f'<div class="lim-title">{titulo}</div>'
                f'<div class="lim-desc">{desc}</div>'
                f'</div>',
                unsafe_allow_html=True,
            )

    st.markdown(
        '<div style="margin-top:24px;font-family:DM Mono,monospace;font-size:9px;'
        'color:rgba(232,230,224,0.2);line-height:1.8">'
        'Referencia: Yan et al. (2020) · arXiv:2001.04063 · Sección 5<br>'
        'microsoft/prophetnet-large-uncased-cnndm · HuggingFace Hub'
        '</div>',
        unsafe_allow_html=True,
    )
    st.markdown('</div>', unsafe_allow_html=True)